[package]
name = "keyboard-layout-generator"
version = "0.1.0"
authors = ["Carolin Brandt <carolin.brandt@tum.de>"]
edition = "2018"

[dependencies]
csv = "1"
failure = "0.1"
serde = "1"
serde_derive = "1"
structopt = "0.2"
t4rust-derive = { git = "https://github.com/ReSpeak/t4rust"}
